#!/bin/sh
# Deploy plugins + secrets to Kobo (USB-mounted).
set -eu

C_RESET='\033[0m'
C_INFO='\033[1;34m'
C_SUCCESS='\033[1;32m'
C_WARN='\033[1;33m'
C_ERROR='\033[1;31m'
C_DIM='\033[2;37m'

# Prompt for sudo early so output redirection doesn't hide the password prompt
if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
	sudo -v || true
fi

TOTAL_STEPS=6
CURRENT_STEP=0

step() {
	CURRENT_STEP=$((CURRENT_STEP + 1))
	local label=$1
	local width=30
	local filled=$((CURRENT_STEP * width / TOTAL_STEPS))
	local empty=$((width - filled))

	local bar=""
	local i=0
	while [ $i -lt $filled ]; do
		bar="${bar}█"
		i=$((i + 1))
	done

	local spaces=""
	i=0
	while [ $i -lt $empty ]; do
		spaces="${spaces}░"
		i=$((i + 1))
	done

	printf "\r\033[2K${C_INFO}[${C_SUCCESS}%s${C_DIM}%s${C_INFO}] %s/%s : ${C_RESET}%s" "$bar" "$spaces" "$CURRENT_STEP" "$TOTAL_STEPS" "$label"
}

. "$(dirname "$0")/kobo-lib.sh"

kobo_cleanup_wrap() {
	printf "\n"
	kobo_cleanup >/dev/null 2>&1 || true
}
trap kobo_cleanup_wrap EXIT INT TERM

KOBO_SSH=""
KOBO_SSH_PORT="2222"

PLUGIN_MARKDOWN="plugins/markdownreader.koplugin"
PLUGIN_SYNCNOTES="plugins/syncnotes.koplugin"
PLUGIN_FLASHCARDS="plugins/flashcards.koplugin"

# --- Step 1: Build native math backend (optional) ---
step "Building native math backend..."
if [ -f "$PLUGIN_MARKDOWN/Makefile" ]; then
	cd "$PLUGIN_MARKDOWN"
	HAS_TOOLCHAIN=0
	command -v zig >/dev/null 2>&1 && HAS_TOOLCHAIN=1
	if [ -x "/home/denial/Projects/kobo-notes/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++" ] || command -v arm-none-linux-gnueabihf-g++ >/dev/null 2>&1; then
		HAS_TOOLCHAIN=1
	fi
	if [ "$HAS_TOOLCHAIN" -eq 1 ]; then
		# zig cross-compiles without a local arm toolchain; otherwise use the
		# arm-none-linux-gnueabihf-g++ found above.
		if command -v zig >/dev/null 2>&1; then
			(make clean >/dev/null 2>&1 && make KOBO_CXX="zig c++ -target arm-linux-gnueabihf.2.19" kobo >/dev/null 2>&1) || (
				printf "\n${C_ERROR}Build failed!${C_RESET}\n"
				exit 1
			)
		else
			(make clean >/dev/null 2>&1 && make kobo >/dev/null 2>&1) || (
				printf "\n${C_ERROR}Build failed!${C_RESET}\n"
				exit 1
			)
		fi
		mv kobo-libmicrotex.so libmicrotex.so
	else
		# No cross-compiler available. The MicroTeX backend is a pure-Lua change now
		# (glyphs are converted to SVG paths in Lua), so we only need the existing
		# libmicrotex.so on the device, which deploy_plugin's cp -r preserves.
		printf "\n${C_WARN}No cross-compiler (zig/arm-none-linux-gnueabihf-g++) found; keeping existing libmicrotex.so on device.${C_RESET}\n"
	fi
	cd - >/dev/null

fi

# --- Step 2: Locate and mount the Kobo ---
step "Locating and mounting Kobo..."
kobo_mount >/dev/null 2>&1 || (
	printf "\n${C_ERROR}Failed to mount Kobo!${C_RESET}\n"
	exit 1
)

# --- Step 3: Clean caches & rendered folders ---
step "Cleaning caches and rendered folders..."
# Remove all .rendered directories and their contents anywhere under KOBO_MOUNT
find "$KOBO_MOUNT" -type d -name ".rendered" -prune 2>/dev/null | while IFS= read -r _dir; do
	[ -d "$_dir" ] && maybe_sudo rm -rf "$_dir" 2>/dev/null || true
done

# Clean legacy HTML cache and sidecars
if [ -d "$KOBO_HTML_CACHE" ]; then
	maybe_sudo rm -rf "$KOBO_HTML_CACHE"/*.html 2>/dev/null || true
	maybe_sudo rm -rf "$KOBO_HTML_CACHE"/*.htm 2>/dev/null || true
	for d in "$KOBO_HTML_CACHE"/*.sdr; do
		[ -d "$d" ] && maybe_sudo rm -rf "$d" 2>/dev/null || true
	done
fi

# Clean any standalone generated HTML files marked by markdownreader
_tmp="$(mktemp)"
find "$KOBO_MOUNT" -name "*.html" -type f -exec grep -l "<!-- generated by markdownreader.koplugin -->" {} + >"$_tmp" 2>/dev/null || true
while IFS= read -r f; do
	[ -n "$f" ] && maybe_sudo rm -f "$f" 2>/dev/null || true
done <"$_tmp"
rm -f "$_tmp"

# Clean plugin math cache directory and legacy svg cache
if [ -d "$KOBO_ROOT/markdownreader" ]; then
	maybe_sudo rm -rf "$KOBO_ROOT/markdownreader" 2>/dev/null || true
fi

if [ -d "$KOBO_CACHE/md" ]; then
	maybe_sudo rm -rf "$KOBO_CACHE/md" 2>/dev/null || true
fi

if [ -n "$KOBO_SSH" ]; then
	ssh -p "$KOBO_SSH_PORT" "$KOBO_SSH" "rm -rf /tmp/microtex-cache" 2>/dev/null || true
fi

# --- Step 4: Deploy Files ---
step "Deploying plugins..."
deploy_plugin() {
	_src="$1"
	_name="$(basename "$_src")"
	maybe_sudo cp -r "$_src" "$KOBO_PLUGINS/"
	maybe_sudo rm -rf "$KOBO_PLUGINS/$_name/.git" "$KOBO_PLUGINS/$_name/.gitignore"
}

deploy_plugin "$PLUGIN_MARKDOWN"
deploy_plugin "$PLUGIN_SYNCNOTES"
deploy_plugin "$PLUGIN_FLASHCARDS"

# --- Step 5: Deploy secrets ---
step "Deploying secrets..."
if [ -d secrets ]; then
	maybe_sudo mkdir -p "$KOBO_SECRETS"
	maybe_sudo cp -r secrets/* "$KOBO_SECRETS/"
fi

# --- Step 6: Sync ---
step "Syncing..."
sync

printf "\n${C_SUCCESS}Deploy complete! Safe to disconnect.${C_RESET}\n"
