#!/bin/sh
# Deploy plugins + secrets to Kobo (USB-mounted).
# Builds the optional native math backend first, if a Makefile is present.
# Finds the Kobo by filesystem label, mounts it automatically, copies the
# plugins, and ALWAYS unmounts it on exit — success, mid-script failure, or
# interrupt (EXIT trap). Prompts for sudo if needed.
# Clears generated HTML + math-image caches so render tests start fresh.
set -eu

# Device detection, mounting and the derived KOBO_* paths live in kobo-lib.sh,
# shared with collect-diagnostics.sh.
. "$(dirname "$0")/kobo-lib.sh"

# Always unmount at the end, in any case: even if a later step fails (set -e
# would otherwise exit before the unmount), even if the Kobo was already
# mounted. Never leave the device in a mounted/half-mounted state.
trap kobo_cleanup EXIT INT TERM

# Remote cleanup (SSH to Kobo, optional — set KOBO_SSH to a host string)
# Typical: KOBO_SSH="root@192.168.2.2"  port 2222
# Leave empty to skip remote SVG-cache cleanup.
KOBO_SSH=""
KOBO_SSH_PORT="2222"

PLUGIN_MARKDOWN="plugins/markdownreader.koplugin"
PLUGIN_SYNCNOTES="plugins/syncnotes.koplugin"
PLUGIN_FLASHCARDS="plugins/flashcards.koplugin"

# --- Step 1: Build native math backend (optional) ---
# The math renderer is pure Lua by default and needs no build step.
# A native (MicroTeX) backend is a deferred, optional future addition; if someone
# adds a Makefile to the plugin directory, build it here. Otherwise skip cleanly.
if [ -f "$PLUGIN_MARKDOWN/Makefile" ]; then
	echo "Makefile found — building native math backend for Kobo (ARMhf)..."
	cd "$PLUGIN_MARKDOWN"
	make clean
	make kobo
	mv kobo-libmicrotex.so libmicrotex.so
	cd - >/dev/null
	echo "Build successful."
else
	echo "No Makefile in $PLUGIN_MARKDOWN — skipping native build."
	echo "  (Math rendering is pure Lua; no native library is required.)"
fi
echo ""

# --- Step 2: Locate and mount the Kobo ---
kobo_mount

# --- Step 3: Clean caches (before copy, so fresh start) ---
echo "Clearing HTML cache at $KOBO_HTML_CACHE ..."
if [ -d "$KOBO_HTML_CACHE" ]; then
	# Remove generated HTML files
	maybe_sudo rm -rf "$KOBO_HTML_CACHE"/*.html 2>/dev/null || true
	maybe_sudo rm -rf "$KOBO_HTML_CACHE"/*.htm 2>/dev/null || true
	# Also remove stale KOReader sidecar dirs (bookmarks/progress from old render)
	for d in "$KOBO_HTML_CACHE"/*.sdr; do
		[ -d "$d" ] && maybe_sudo rm -rf "$d" 2>/dev/null || true
	done
	echo "  HTML cache cleared (files + .sdr sidecars)."
else
	echo "  No HTML cache directory found (created on first use)."
fi

# Clean generated HTML files left over in the markdown tree itself from older versions.
# We explicitly check for the plugin's marker comment to avoid deleting real books.
echo "Cleaning legacy generated .html files from the markdown tree..."
find "$KOBO_MOUNT" -name "*.html" -type f -exec grep -l "<!-- generated by markdownreader.koplugin -->" {} + | xargs -r maybe_sudo rm -f

# Clear the math-image cache from onboard storage, if any backend produced one.
# The pure-Lua backend may emit no images at all; this is best-effort cleanup.
echo "Clearing onboard math-image cache at $KOBO_CACHE/md/svg ..."
if [ -d "$KOBO_CACHE/md/svg" ]; then
	maybe_sudo rm -rf "$KOBO_CACHE/md/svg"/*.svg 2>/dev/null || true
	echo "  Onboard math-image cache cleared."
else
	echo "  No math-image cache directory found on onboard storage."
fi

# Remote cleanup of the legacy /tmp math cache (optional, requires network on Kobo).
# Current design caches under KOReader's cache dir on onboard storage (cleared
# above); this only mops up leftovers from older /tmp-based runs.
if [ -n "$KOBO_SSH" ]; then
	echo "Clearing legacy remote cache at ${KOBO_SSH}:/tmp/microtex-cache/ ..."
	ssh -p "$KOBO_SSH_PORT" "$KOBO_SSH" "rm -rf /tmp/microtex-cache" 2>/dev/null &&
		echo "  Legacy remote cache cleared." ||
		echo "  SSH cleanup failed (Kobo not reachable? skipping)."
else
	echo "Math cache note: rendered math is cached on onboard storage"
	echo "  ($KOBO_CACHE/md/) and cleared above. Any legacy /tmp cache clears on reboot."
fi

# --- Step 4: Deploy Files ---
echo "Deploying plugins..."
# Copy only plugin sources. The plugins are git submodules, so a plain `cp -r`
# drags a `.git` file onto the device; the Kobo has no git and it just confuses
# later inspection. Copy the directory, then drop VCS metadata.
deploy_plugin() {
	_src="$1"
	_name="$(basename "$_src")"
	maybe_sudo cp -rv "$_src" "$KOBO_PLUGINS/"
	maybe_sudo rm -rf "$KOBO_PLUGINS/$_name/.git" "$KOBO_PLUGINS/$_name/.gitignore"
}

deploy_plugin "$PLUGIN_MARKDOWN"
deploy_plugin "$PLUGIN_SYNCNOTES"
deploy_plugin "$PLUGIN_FLASHCARDS"

echo "Deploying secrets..."
if [ -d secrets ]; then
	maybe_sudo mkdir -p "$KOBO_SECRETS"
	maybe_sudo cp -rv secrets/* "$KOBO_SECRETS/"
fi

echo "Syncing..."
sync

echo "Done."
echo ""
# Unmounting happens automatically via the EXIT trap set up at the top of this
# script (kobo_cleanup), so it also runs when an earlier step fails or the
# script is interrupted.
