#!/usr/bin/env python3
"""Generate math_glyph_paths.lua for the MicroTeX SVG post-processor.

We bake FreeSerif glyph *outlines* (SVG path `d` strings) for the codepoints
MicroTeX emits into its SVG <text> elements.  This lets the plugin convert
`<text>&#cp;</text>` into font-independent `<path>` outlines on-device, so
rendering no longer depends on a math font being installed or on the SVG
engine resolving `font-family` (which KOReader's crengine does not do reliably).

FreeSerif is chosen because it covers every codepoint the MicroTeX SVGs emit
(verified) and its serif style is closest to XITS/Computer Modern.

Usage:
    gen_glyph_paths.py --out <math_glyph_paths.lua> [--font <font.ttf>] [--svg-dir <dir>]

By default it scans every *.svg under the supplied --svg-dir (or the plugin's
rendered math_svg dir) to collect the full codepoint set actually used.
"""

import argparse
import glob
import os
import re
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

DEFAULT_FONT = "/home/denial/Mount/KOBO/.adds/koreader/fonts/freefont/FreeSerif.ttf"
DEFAULT_SVG_DIR = os.path.expanduser(
    "~/Mount/KOBO/.adds/koreader/notes/AI-2526/eliva/.rendered/math_svg"
)


def collect_codepoints(svg_dir):
    cps = set()
    for f in glob.glob(os.path.join(svg_dir, "*.svg")):
        txt = open(f, encoding="utf-8", errors="replace").read()
        for m in re.finditer(r"&#([0-9]+);", txt):
            cps.add(int(m.group(1)))
    return sorted(cps)


def load_font(fontfile):
    font = TTFont(fontfile)
    upm = font["head"].unitsPerEm
    cmap = {}
    for t in font["cmap"].tables:
        if t.isUnicode():
            for cp, g in t.cmap.items():
                cmap.setdefault(cp, g)
    return upm, cmap, font.getGlyphSet()


def glyph_path(gs, gname):
    pen = SVGPathPen(gs)
    gs[gname].draw(pen)
    return pen.getCommands()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--svg-dir", default=DEFAULT_SVG_DIR)
    ap.add_argument("--codepoints", help="comma-separated extra codepoints")
    args = ap.parse_args()

    cps = collect_codepoints(args.svg_dir)
    if args.codepoints:
        cps += [int(x) for x in args.codepoints.split(",")]
    cps = sorted(set(cps))

    upm, cmap, gs = load_font(args.font)
    lines = [
        "-- Auto-generated by tools/gen_glyph_paths.py. Do not edit by hand.",
        "-- FreeSerif glyph outlines (GPL) baked to remove the runtime font dependency.",
        "local M = { upm = " + str(upm) + " }",
        "M.paths = {",
    ]
    missing = []
    for cp in cps:
        gname = cmap.get(cp)
        if not gname:
            missing.append(cp)
            continue
        d = glyph_path(gs, gname)
        lines.append('    [%d] = "%s",' % (cp, d))
    lines.append("}")
    lines.append("return M")
    open(args.out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("wrote", args.out, "for", len(cps), "codepoints; upm", upm)
    if missing:
        print(
            "MISSING glyphs:",
            " ".join("U+%04X" % c for c in sorted(missing)),
            file=sys.stderr,
        )
        sys.exit(1)  # incomplete coverage must fail the regen run loudly


if __name__ == "__main__":
    main()
