#!/usr/bin/env python3
import argparse
import glob
import os
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

DEFAULT_FONTS_DIR = "/home/denial/Projects/kobo-notes/plugins/markdownreader.koplugin/res/fonts"

def load_font(fontfile):
    font = TTFont(fontfile)
    upm = font["head"].unitsPerEm
    cmap = {}
    for t in font["cmap"].tables:
        if t.isUnicode() or t.platformID == 0 or t.platformID == 3:
            for cp, g in t.cmap.items():
                cmap.setdefault(cp, g)
    return upm, cmap, font.getGlyphSet()

def glyph_path(gs, gname):
    pen = SVGPathPen(gs)
    gs[gname].draw(pen)
    return pen.getCommands()

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--fonts-dir", default=DEFAULT_FONTS_DIR)
    args = ap.parse_args()

    lines = [
        "-- Auto-generated by tools/gen_glyph_paths.py. Do not edit by hand.",
        "-- Glyph outlines baked from MicroTeX bundled fonts to remove the runtime font dependency.",
        "local M = {}",
        "M.fonts = {",
    ]

    ttf_files = glob.glob(os.path.join(args.fonts_dir, "**/*.ttf"), recursive=True)
    if not ttf_files:
        print(f"Error: No TTF files found in {args.fonts_dir}", file=sys.stderr)
        sys.exit(1)

    for fontfile in sorted(ttf_files):
        font_name = os.path.splitext(os.path.basename(fontfile))[0]
        try:
            upm, cmap, gs = load_font(fontfile)
        except Exception as e:
            print(f"Failed to load {fontfile}: {e}", file=sys.stderr)
            continue
        
        lines.append(f'    ["{font_name}"] = {{')
        lines.append(f'        upm = {upm},')
        lines.append('        paths = {')
        
        for cp in sorted(cmap.keys()):
            gname = cmap[cp]
            if gname == ".notdef" or gname == ".null": continue
            try:
                d = glyph_path(gs, gname)
                # Omit empty paths to save space
                if d and d != "":
                    lines.append(f'            [{cp}] = "{d}",')
            except Exception as e:
                pass
                
        lines.append('        }')
        lines.append('    },')

    lines.append("}")
    lines.append("return M")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    
    print(f"wrote {args.out} for {len(ttf_files)} fonts")

if __name__ == "__main__":
    main()
